# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=64)),
                ('author_mail', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-author_name'],
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-category_name'],
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=256)),
                ('post_content', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.Author')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_page.Category')),
            ],
            options={
                'ordering': ['-post_date'],
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
